export const animate: string;
export const btnWrapper: string;
export const chosen: string;
export const course: string;
export const courseWrapper: string;
export const filtersWrapper: string;
export const sliderArrow: string;
export const switchAnimation: string;
export const wrapper: string;
