/* application constants that coudn't be replaced by enums */
// supported languages
export const LANGUAGES = ['en', 'fr', 'pl'];

export const DEFAULT_VALUES = {
    pageSize: 50,
    maxRows: 15,
};

// just for testing purposes
export const TESTING_TOKEN_MOCK =
    // eslint-disable-next-line max-len
    'eyJ4NXQiOiJZVEE1TURFNE5tSmhOVFZrTVRjellXTmxPR1UxT0Rrek1tTXdaRE5sT1RSaE4yRXdPR1E1TVRabFl6RTVaR0k1Wm1GaE5qWTFOV0U1WXpFd1lXUTRNdyIsImtpZCI6IllUQTVNREU0Tm1KaE5UVmtNVGN6WVdObE9HVTFPRGt6TW1Nd1pETmxPVFJoTjJFd09HUTVNVFpsWXpFNVpHSTVabUZoTmpZMU5XRTVZekV3WVdRNE13X1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJjYW0iLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwiYXVkIjpbIjRYS3Z3ZTNXZE5zYTZXZ1RLTmlGYjR1WGF6OGEiLCJzZHhwbCJdLCJuYmYiOjE2ODIzMzA4MTQsImF6cCI6IjRYS3Z3ZTNXZE5zYTZXZ1RLTmlGYjR1WGF6OGEiLCJwZXJtaXNzaW9ucyI6WyJDQ0RPIiwiQ0NTRSJdLCJzY29wZSI6Im9wZW5pZCIsImlzcyI6Imh0dHBzOlwvXC93c28taXMuZGV2cGwtYXp1cmUuc3R5cmF4LmN6OjQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTY4MjMzNDQxNCwiaWF0IjoxNjgyMzMwODE0LCJqdGkiOiI5MTc4ZTdkNi0xNzhhLTRkMzgtOGY2OC0zY2Q0ZDliNjE4YjUifQ.ivhEPe9Umvhf52MtZ8mPgqHen7IVn8IcI2zmGivPjggMRGRro5hm3B06H170qzCwaG4WJbwfEiIgUOEZi5RgHzsddxRQPqim1qsuuU2d4ypIV91vXh4td5KoI3_Ad5xP3lfZWoxCZr_6sFaGhBth9R9xULarjcVu9gyF3u3QjaPMGVT3u8Nvn3LAKmqqKwv_Db4V5SVBwLPkB6jH1Gr8GDvPIFRJyW4KU2o1tWab88cM0tmLGfx4uVQse7chBRNmBAbZQlD2mfdnDzfJVcDXjioCnVtjSmzZ5XS6qxYPLpEPnTiGQUosb6_lSPS_TiTfoRj1v2Eye7r3jB0lu6Edlw';
export const PERMISSIONS_MOCK = ['CCSE', 'CCDO', 'CCOH', 'CTHN', 'CCRP', 'CCSU', 'CWSU', 'CCTP', 'CCDB', 'CRSP'];

// it doesnt make any sense, should be done on BE but management decided
export const REPLACE_TEXT = 'Not Applicable';

export const TRANSACTION_ACTION_CODE = {
    '000': 'Approved',
    '001': 'Approved with ID',
    '003': 'Approved VIP',
    '004': 'Approved, Track III updated',
    '007': 'Approved update chip',
    '085': 'No reason to declined',
    '0P5': 'PIN Unblock request declined NOT IN SPL SCOPE',
    '0P6': 'PIN Change request declined NOT IN SPL SCOPE',
    '100': 'Rejected',
    '101': 'Expired card',
    '102': 'Suspected fraud.  same as 129',
    '104': 'Private card',
    '106': 'PIN entry tries exceeded',
    '107': 'Refer to card issuer',
    '108': 'Refer to issuer; special condit',
    '109': 'Invalid Merchant',
    '110': 'Invalid amount',
    '111': 'Invalid card number',
    '112': 'PIN element required',
    '114': 'Unknown card',
    '115': 'Function not available',
    '116': 'No sufficient funds',
    '117': 'Incorrect PIN',
    '118': 'No such card',
    '119': 'Cardholder trx not permitted',
    '120': 'Terminal trx not permitted',
    '121': 'Exceeds permitted trans limit',
    '122': 'Security violation',
    '123': 'Frequency exceeded',
    '125': 'Card not in service',
    '126': 'Wrong PIN format',
    '127': 'Error PIN length',
    '128': 'Cryptographic error',
    '129': 'Suspected fraud',
    '146': 'Retry pin nbr already exceeded',
    '180': 'No credit account',
    '181': 'No cheque account',
    '182': 'No saving Account',
    '183': 'Bad CVV',
    '184': 'Invalid date',
    '185': 'Service code not supported',
    '199': 'Refused with Track III updating',
    '200': 'Rejected, Pick up card',
    '201': 'Expired card, Pick up',
    '202': 'Fraudulent, Pick up',
    '204': 'Private card, Pick up',
    '205': 'Call security acquirer, pick up',
    '206': 'PIN entry tries exceeded',
    '207': 'Special conditions, Pick up',
    '208': 'Lost card, Pick up',
    '209': 'Stolen card, Pick up',
    '210': 'Suspected fraud, Pick up',
    '280': 'Alternate Amount cancelled',
    '299': 'Pick up',
    '300': 'Successfully processed',
    '301': 'Not supported by the addressee',
    '302': 'Record not found  in the file',
    '303': 'Duplicate record. Same as 308',
    '304': 'Fields control error',
    '305': 'Locked table',
    '306': 'Unsuccessful',
    '307': 'Format error',
    '308': 'Duplicate record.',
    '309': 'Unknown file',
    '381': 'Record not found',
    '382': 'Acct not stopp. Withdraw no proc',
    '383': 'Delete Balance record',
    '385': 'Balance inquiry',
    '480': 'Reversal accepted',
    '481': 'Invalid reversal',
    '482': 'Original Transaction Already Rev',
    '484': 'Rev Amount Mismatch',
    '485': 'Rev WRONG PAN',
    '501': 'Reconciliation Not Accepted',
    '503': 'Counters not available',
    '581': 'Reconciliation done',
    '582': 'Reconcil. process not available',
    '800': 'Cut-off in progress',
    '880': 'Connection not accepted',
    '881': 'Download Hot list',
    '882': 'Update parameters file',
    '883': 'Update application file',
    '884': 'Update screens file',
    '885': 'Update bin tables',
    '888': 'Send of cut-of',
    '891': 'TPK transfer',
    '892': 'TMK transfer',
    '893': 'MAC transfer',
    '898': 'ATM reboot',
    '899': 'OK, no action',
    '902': 'Invalid transaction',
    '903': 'Start of transaction',
    '908': 'Not such issuer',
    '909': 'System fault',
    '911': 'Time out',
    '912': 'Issuer not available',
    '992': 'No Connection',
    '993': 'Pin verification fault',
    '994': 'Transaction processing fault',
    '995': 'Server processing fault',
    '444': 'Invalid domain ',
    '555': 'Invalid timeframe',
    '124': 'Contactless counter exceeded',
    '606': 'limit default undefined',
};
