export declare const animationChangeCard: string;
export declare const blockHoveredLeftWrong: string;
export declare const blockHoveredRightCorrect: string;
export declare const cardPage: string;
export declare const cardPhrase: string;
export declare const cardWrapper: string;
export declare const changeCard: string;
export declare const controlsSeparator: string;
export declare const translationSeparator: string;
