export const filterItem: string;
export const filterLabel: string;
export const focused: string;
export const formInput: string;
export const formItem: string;
export const formLabel: string;
export const invalidInput: string;
export const label: string;
export const withoutLabel: string;
