export const active: string;
export const big: string;
export const button: string;
export const disabled: string;
export const easingIn: string;
export const fullLine: string;
export const link: string;
export const small: string;
export const tooltip: string;
