export const gridCol_1: string;
export const gridCol_2: string;
export const gridCol_3: string;
export const gridCol_4: string;
export const gridCol_5: string;
export const gridCol_6: string;
export const gridColumn: string;
export const gridRow: string;
export const modal: string;
